name: Packer

on:
  
  pull_request:
      branches: [main]

  workflow_dispatch:

jobs:
  packer-validate:
    name: Packer Validate
    runs-on: ubuntu-latest

    steps:
          
      - uses: actions/checkout@v3
      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer
      - name: Packer Init
        run: "packer init ./ami-jenkins.pkr.hcl"
      - name: Packer Validate
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: "packer validate -var=GH_TOKEN=\"$GH_TOKEN\" -var=DOCKER_TOKEN=\"$DOCKER_TOKEN\" ./ami-jenkins.pkr.hcl"
        

